### PR TITLE
Normalize non unicode

### PR DESCRIPTION
**Pull request by cohendekel**
possible fix for #10

### CODE REVIEW

**Comment by redsk** [comment]
@cohendekel , great catch, with `IDN.ALLOW_UNASSIGNED` it seems to work with other emoji-urls I have without requiring the `icu4j` library. 

I have to admit I have no idea what are the potential differences between `IDN.ALLOW_UNASSIGNED` and using `icu4j`... :)

**Comment by redsk** [comment]
On the other hand, this library's jar is 35kb (https://mvnrepository.com/artifact/io.github.url-detector/url-detector/0.1.22) while `icu4j`'s is 12.5MB! (https://mvnrepository.com/artifact/com.ibm.icu/icu4j/67.1)

**Comment by cohendekel** [comment]
i agree, 
not sure its worth switching to if we can solve it within the existing API.
I really appreciate you taking the time reporting on the issue and suggestion solution.
🥇

**Comment by redsk** [comment]
@cohendekel you're more than welcome, and thanks for taking care of this library, I find it very useful. 

Trying to understand these standards, sent me down a *crazy* rabbit hole... actually, there are *three* standards:
- old IDNA2003 [rfc3490](https://tools.ietf.org/html/rfc3490), [rfc3491](https://tools.ietf.org/html/rfc3491)
- "new" IDNA2008 [rfc5890](https://tools.ietf.org/html/rfc5890), [rfc5891](https://tools.ietf.org/html/rfc5891), [rfc5892](https://tools.ietf.org/html/rfc5892), [rfc5893](https://tools.ietf.org/html/rfc5893), [rfc5894](https://tools.ietf.org/html/rfc5894), [rfc5895](https://tools.ietf.org/html/rfc5895)
- [UTS #46](http://www.unicode.org/reports/tr46/), Unicode IDNA Compatibility Processing.

The latter "standard" is a sort of more lenient, transitional standard in between IDNA2003 and IDNA2008, that tries to accommodate both IDNAs. However, this is not really completely feasible in the first place: see (important) the [comparison table](http://www.unicode.org/reports/tr46/#Table_IDNA_Comparisons).

A key difference among the three "standards" are the use of symbols (including emojis) that are allowed in IDNA2003 and UTS46 but *forbidden* in IDNA2008.

To further complicate matters, UTS46 has two [processing algorithms](http://www.unicode.org/reports/tr46/#Processing):
- Transitional, among other things, maps German letter "ß" to "ss": http://www.rößner.de/ is changed to https://www.roessner.de/
- Nontransitional, among other things, does *not* map to "ß" to "ss": http://www.rößner.de/ stays http://www.rößner.de/
http://www.rößner.de/ and https://www.roessner.de/ are two existing, different, and unrelated websites that, depending on the standard used, are both resolved from http://www.rößner.de/ !

## So my question is, what are browsers doing? 

Emojis and sybols are cleary supported in all major browesers (Firefox, Chrome, Safari, Edge) and they work. IDNA2003 allows unassigned code points in lookup but not registration. These are in the section of the table under "Unicode 4.0 to Unicode 11.0", and marked as LookupValid. From this, I undertand that browsers and registrars, including https://i❤.ws/ which specializes in domains with emojis, are not using IDNA2003 nor IDNA2008. They are using UTS46, for which emojis are valid.

Transitional or Nontransitional? I tried with the latest version of these browsers 

- Firefox ( Gecko) nontransitional
- Safari (Webkit) nontransitional
- Chrome (Blink engine) transitional (issue)(https://bugs.chromium.org/p/chromium/issues/detail?id=505262&thanks=505262&ts=1435488604)
- Edge (also Blink) transitional
- Bonus: whatsapp nontransitional

With icu4j we could use both processings (and has more options):
```
// sorry, Scala code
import com.ibm.icu.text.IDNA
val domain  = "www.rößner.de/"

val uts46trans = IDNA.getUTS46Instance(IDNA.DEFAULT) // Transitional
println(uts46trans.nameToASCII(domain, new java.lang.StringBuilder(), new IDNA.Info()).toString)
// www.xn--rssner-wxa.de/ -> https://www.roessner.de/ (after redirect)

val uts46nontrans = IDNA.getUTS46Instance(IDNA.NONTRANSITIONAL_TO_ASCII)
println(uts46nontrans.nameToASCII(domain, new java.lang.StringBuilder(), new IDNA.Info()).toString)
// www.xn--rner-vna1l.de/ -> http://www.rößner.de/ 
```

## What would I expect from `URL-Detector`?
My use case is URL detection in large amount of text, often for malicious users detection. For me, it's important to be able to detect URLs that are handled by major browsers.

Ideally, `url.normalize()` would take as option the same option that `icu4j` takes, so the user would have the possibility to choose the desired behaviur. Maybe we could add `icu4j` as an optional dependency with fallback to `IDN.ALLOW_UNASSIGNED` for those who mind the added size?

**Comment by pgalbraith** [comment]
Seems like an elegant solution to me, I will commit.  Thanks!

**Pull request merged**
