### PR TITLE
Add support for absolute positioning to know where the URL was

### PR DESCRIPTION
**Pull request by makkarpov**
Sometimes you need not only URL itself, but also a position of that URL in source string.

This PR implements position annotations: you can use `getAbsoluteIndex()` to retrieve the offset from URL.

Unit tests were updated with index correctness checks. All existing test samples pass these indexing tests.

### CODE REVIEW

**Comment by pgalbraith** [comment]
Thanks for the submission!  Can you add some documentation to the new method in the Url class?  I'm also curious, what is the significance of "absolute index" vs. just "index"?

**Comment by makkarpov** [comment]
Just index is a position of URL part relative to start of the URL. E.g you have `http://x` and `x` is positioned at index 7. This is (as I understand) how indices work.

Absolute index is a position of URL in the string itself. So you can, for example, gather a context where URL appears. Originally parser didn't provided that information.

BTW I had adding Javadoc comment to the method.

**Comment by cohendekel** [comment]
I understand the motivation for it, but Isn't it a bit strange we keep index to something we don't own?
Meaning AFAIK, ```Url``` object does not hold the original text it derived from, so why would it keep the index from it?

**Comment by makkarpov** [comment]
Yes, it does not hold whole original text, but user probably does. I don't think that there is more elegant way to return position to user.

**Comment by pgalbraith** [comment]
@cohendekel I see your point, but I also can see that this may nontheless be useful info to have, and I can't think of a more elegant way to get this information back to the user.

I'm still pondering over the name, though, maybe there's a better member name to indicate this is a pointer into external data.

**Comment by cohendekel** [comment]
Maybe something like ```offsetFromOriginalText```.
If its that important (which im not sure is the case) we can consider storing also the original text in ```Url```.
But i'm still not convinced its the right path to go, can you provide me an example where the caller can't resolve it by him/her self as elegantly?

**Comment by pgalbraith** [comment]
I agree in principal but I think this is enough of an exceptional case to warrant not copying the text because the original string could be huge.  And for that reason having to redo the search again to find the location would be needlessly inefficient if we've already just done that search.  If there's a legitimate need to know the location than I think it's worth returning.  I can't think of a use for this information myself, but that hardly means there isn't one.

**Comment by pgalbraith** [comment]
@makkarpov please take a look at the comments on the above revert, I had problems when I tried to merge this PR.

**Pull request merged**
