### PR TITLE
Fix null pointer exception in both UrlDetector() and Url.create

### PR DESCRIPTION
**Pull request by redsk**
As in title.

### CODE REVIEW

**Comment by pgalbraith** [comment]
Does https://github.com/URL-Detector/URL-Detector/pull/11 satisfactorily solve the same issue?

**Comment by redsk** [comment]
No, the last commit in this PR solves the issue. I've created 4 PR, they all include all commits from #11 onward.

**Comment by pgalbraith** [comment]
Would you mind separating the commits so each PR addresses a single issue?

**Comment by redsk** [comment]
@pgalbraith can you have a look at #12 first please? So if PRs get merged in the correct order there's no need for rebase.

**Pull request closed without merging**
